CC = gcc
CFLAGS = -I
LIBS = -lm
TEST = test
INDEX? = index

# Header file
DEPS = $(wildcard lib/*.h)

# Source file
source = $(wildcard src/*.c)
source_services = $(wildcard src/services/*.c)
source_ultilities = $(wildcard src/ultilities/*.c)
source_validations = $(wildcard src/validations/*.c)
source_tests = $(wildcard tests/*.c)

# Object file
services = $(patsubst %.c,%.o,$(source_services))
ultilities = $(patsubst %.c,%.o,$(source_ultilities))
validations = $(patsubst %.c,%.o,$(source_validations))
tests = $(patsubst %.c,%.o,$(source_tests))

# Lib
libs = $(services) $(ultilities) $(validations)

# Run command
all: $(SERVER) $(CLIENT)

$(TEST): tests/$(INDEX).o $(libs)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< 

clean: $(lib) $(SERVER) $(CLIENT)
	rm -rf $(lib) $(SERVER) $(CLIENT)

# Run test
# make -f target INDEX=<filename>